export const plans = [
  {
    name: "JARVIS",
    price: "R$19,90",
    period: "/mês",
    tagline: "Organiza sua vida",
    features: [
      "Chat ilimitado (texto, áudio, foto, PDF)",
      "Agenda inteligente com sync bidirecional",
      "Google Calendar, Apple, Outlook",
      "Resumo matinal essencial",
      "Lembretes ilimitados com checklist",
      "Cofre de documentos (CPF, RG, convênio)",
      "Controle financeiro (registro de gastos)",
      "Listas e notas contextuais",
      "Perfil contextual (família, pets, trabalho)",
      "3 /faz por mês",
    ],
    cta: "Teste grátis por 7 dias",
    footnote: "Inclui 3 /faz por mês\npra você provar que funciona",
    popular: false,
  },
  {
    name: "JARVIS /FAZ",
    price: "R$69,90",
    period: "/mês",
    tagline: "Executa por você",
    features: [
      "Tudo do Jarvis",
      "/faz ilimitado",
      "Agendamento autônomo (Doctoralia e mais)",
      "Busca de voos (milhas + dinheiro + seats.aero)",
      "Busca na região (convênio, VR/VA, Waze)",
      "Cancelamento de serviços",
      "Reserva de restaurantes",
      "Resumo matinal completo",
      "Cofre ativo (usa docs em agendamentos)",
      "Financeiro completo (relatórios + projeção)",
    ],
    cta: "Começar grátis",
    footnote: "Tudo que o Jarvis faz,\nmas ele age por você.",
    popular: false,
  },
  {
    name: "FULL JARVIS",
    price: "R$119,90",
    period: "/mês",
    tagline: "Seu assistente executivo",
    features: [
      "Tudo do /Faz",
      "Ligações por voz (SAC, clientes, consultas)",
      "Rascunhos no seu tom (email, WhatsApp, SMS)",
      "CRM relacional (importância, padrões, nudges)",
      "Follow-ups proativos (médico, cliente, amigo)",
      "Lembretes inteligentes com trânsito real",
      "5 perfis de personalidade",
      "Preparação proativa de eventos",
      "Dashboard de memória",
      "Suporte prioritário",
    ],
    cta: "Começar grátis",
    footnote: "Assistente executivo completo.\nCancela quando quiser.",
    popular: true,
  },
];
