export const plans = [
  {
    name: "JARVIS",
    price: "R$19,90",
    period: "/mês",
    tagline: "Organiza sua vida",
    features: [
      "Chat ilimitado (texto, áudio, foto, PDF)",
      "Agenda inteligente com sync bidirecional",
      "Google Calendar, Apple, Outlook",
      "Resumo matinal essencial",
      "Lembretes ilimitados com checklist",
      "Cofre de documentos (CPF, RG, convênio)",
      "Controle financeiro (registro de gastos)",
      "Listas e notas contextuais",
      "Perfil contextual (família, pets, trabalho)",
      "3 /faz por mês",
    ],
    cta: "Teste grátis por 7 dias",
    footnote: "Inclui 3 /faz por mês\npra você provar que funciona",
    popular: false,
  },
  {
    name: "JARVIS /FAZ",
    price: "R$69,90",
    period: "/mês",
    tagline: "Executa por você",
    features: [
      "Tudo do Jarvis",
      "/faz ilimitado",
      "Ligações por voz (SAC, clientes, consultas)",
      "Agendamento autônomo (Doctoralia e mais)",
      "Busca de voos (milhas + dinheiro + seats.aero)",
      "Busca na região (convênio, VR/VA, Waze)",
      "Cancelamento de serviços",
      "Resumo matinal completo",
      "Cofre ativo (usa docs automaticamente)",
      "Financeiro completo (relatórios + projeção)",
      "Follow-ups proativos",
    ],
    cta: "Começar grátis",
    footnote: "Cancela quando quiser.\nSem compromisso.",
    popular: true,
  },
];
